"""update db

Revision ID: 7ba15c82a635
Revises: 040177acb3ae
Create Date: 2016-11-26 18:48:27.517191

"""

# revision identifiers, used by Alembic.
revision = '7ba15c82a635'
down_revision = '040177acb3ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
